### ISSUE TITLE
Značky na krátkých linií - nezobrazovat 

### ISSUE THREAD

**Issue by rmakovec** [raugustyn/BetaNM#12]
Jde v QGISu nastavit, že když je linie moc krátká, tak se značka (na cetrálním bodě, po intervalu) nezobrazí???

**Comment by raugustyn** [comment]
No, asi se budou muset udělat dvě vrstvy - pro dlouhý a krátký linie. Podívám se na to a uvidím.

**Comment by raugustyn** [comment]
Nakonec to bez problémů půjde jako jedna vrstva, jednoduše bude zobrazená RuleBased. V prvním pravidle bude definice čáry a druhé pravidlo bude mít omezení na délku a teprve když bude větší tak se zobrazí pouze ta šípka.

Příklad viz projekt Heap/TestProject05.qgs
![](https://raw.githubusercontent.com/raugustyn/BetaNM/master/Heap/GeometryLengthBasedRule.png)

Zatím ale ta délka jsou nějaký hausnumera
![](https://raw.githubusercontent.com/raugustyn/BetaNM/master/Heap/KratkeCaryBezSipekPodivneDelky.png)

**Comment by raugustyn** [comment]
Tak nevím, zkusím zítra :-(

**Comment by raugustyn** [comment]
Su blbej, udělal jsem vrstvu ve stupních :-) :-)

**Comment by raugustyn** [comment]
Tak aso jo:

![](https://raw.githubusercontent.com/raugustyn/BetaNM/master/Heap/GeometryLengthBasedRuleValid.png)

![](https://raw.githubusercontent.com/raugustyn/BetaNM/master/Heap/SipkyNaKonciPodleDelky.png)

Příklad viz projekt Heap/TestProject05.qgs
