### ISSUE TITLE
SVG značky obsahující text

### ISSUE THREAD

**Issue by rmakovec** [raugustyn/BetaNM#13]
SVG značky, které obsahují text se nezobrazí správně. Jde o značky 3.01-Orná půda (r), 4.06-Nádvoří (d) a severka (S). 
První dvě obsahují pouze text - nezobrazí se
Severka obsahuje linie a text - linie se zobrazí, text ne

Pokud v QGISu použiji textovou značku místo SVG, tak při oddálení kresby jsou texttové značky pořád vidět, přestože jsou v mapových jednotkách (pevné) a už jsem dost daleko

**Comment by raugustyn** [comment]
Ty značky jsou asi blbě nakreslený, moje z projektu Misc/TestProject06.qgs funguje:

![](https://raw.githubusercontent.com/raugustyn/BetaNM/master/Heap/SVGZnackySTextem.png)

**Comment by raugustyn** [comment]
Hm, tahle značka sice byla blbě namalovaná

![](https://raw.githubusercontent.com/raugustyn/BetaNM/master/Heap/OrnaPudaWrongSVG.png)

Ale ani po opravení mi to nefunguje

![](https://raw.githubusercontent.com/raugustyn/BetaNM/master/Heap/OrnaPudaCorrectSVG.png)

To bude rukama :-(

**Comment by rmakovec** [comment]
nevím kde jste vzal tu značku co jste otevřel, ale byla dobře namalovaná...aspoň co já mám v PC

**Comment by raugustyn** [comment]
Tohle issue zatím nemá nálepku Otestovat, takže zatím nechte, ještě jsem na to nepřišel. Jinak značka je [tady](https://github.com/raugustyn/BetaNM/blob/master/Heap/beer.svg).

Váš lokální repository se přece musí aktualizovat, stačí dát `Pravý tlačítko | Tortoise Git | Git Pull` a otevřít projekt `Misc/TestProject06.qgs`.

**Comment by rmakovec** [comment]
to jsem samozřejmě aktualizoval, i co mám v záloze je dobře, přebíral jí i Tomáš a byla dobře. Možná jste neaktualizoval než jste začal upravovat
ale to je jedno

**Comment by raugustyn** [comment]
hehe, to ne :-) :-). Co se na git jednou dá, to tam zůstane i s časovým razítkem, viz [Orná půda](https://github.com/raugustyn/BetaNM/commits/master/BodoveZnacky/3_01_orna%20puda.svg).

Ale i když jsem jí kosmeticky doladil, stejně se nezobrazí. Von tu značku ale nezobrazí ani git, jako že je asi nějak binárně bedná.

**Comment by raugustyn** [comment]
Tak jsem nevymyslel co přesně je na těch značkách špatně, nakonec jsem písmenka překreslil na kresbu, viz projekt Heap/TestProject08.qgs.

![Znacky pismenka](https://raw.githubusercontent.com/vugtk21/BetaNM/master/Heap/ZnackyPismenka.png)

**Comment by rmakovec** [comment]
a dal jste tu značku někam? mě se ten projekt nezobrazí, když to otvírám z té synchronizované složky GIT co mám na ploše (BetaNM)

**Comment by raugustyn** [comment]
No, značky jsou tady: [3_01_orna_puda_kresba](https://raw.githubusercontent.com/vugtk21/BetaNM/master/BodoveZnacky/3_01_orna_puda_kresba.svg), [4_06_nadvori_kresba](https://raw.githubusercontent.com/vugtk21/BetaNM/master/BodoveZnacky/4_06_nadvori_kresba.svg), [severka_kresba](https://raw.githubusercontent.com/vugtk21/BetaNM/master/BodoveZnacky/severka_kresba.svg)

Projekt je Heap/TestProject08.qgs.

To je někde mezi klávesnicí a židlí, musíte mi to ukázat :-) :-)

**Comment by rmakovec** [comment]
tak asi mi budete muset dát zítra lekci :)
