### ISSUE TITLE
mm vs. mapové jednotky

### ISSUE THREAD

**Issue by raugustyn** [raugustyn/BetaNM#4]
Mák: Mám takový nápad jak to možná vyřeším. Našel jsem totiž, že projekt měl špatně nastavené mapové jednotky. Takže jednoduché značky mám dobře velké. To ale pořád neřeší to s SVG značkou. Dle mě je tam problém s tím "plátnem" SVG značky, ale včera se nám to nepovedlo. Dále k plátnu potřebujeme taky pořešit jak to bude s překrytovou zónou kolem bodové značky (zkracuje linii) potřebujeme určit vztažný bod značky protože některé jsou bodové na lomech linií. Zítra to s Vácou ještě zkusíme, ale jinak budeme potřebovat pomoc.

**Comment by raugustyn** [comment]
Co takhle? [Příprava značky k tisku v měřítku](https://github.com/raugustyn/BetaNM/wiki/P%C5%99%C3%ADpava-zna%C4%8Dky-k-tisku-v-m%C4%9B%C5%99%C3%ADtku)

**Comment by rmakovec** [comment]
Tohle samozřejmě dělám, ale skutečnost nedopovídá. 
Značky mam kreslené v mm přímo v rozměrech, ale pak když je zobrazuji v mapových jednotkách tak jejich velikost neodpovídá. Mam dvě značky, které jsou nakresleny ve stejné velikosti výšky, ale aby byly stejně velké, tak v QGIS mají různé velikosti v mapových jednotkách. A to mám to plátno kolem značky. rozdíl je, že mám nastavené mm a ne pixely. Dále pak nesedí umístění na střed, spodek či vršek značky.

Navíc aktuální případ, že po znovu otevření projektu QGISu se SVG značky nenačtou a je to ztracené. Musím to dělat znovu. Asi to udělám znovu v QGIS 2.4. protože ta 2.8 co je v testování je chybová. Ale vizualizace se tam dělá lépe. Už mi se mi to v tom QGISu ztratilo vícekrát.

**Comment by raugustyn** [comment]
Poslední odstavec poznámky @rmakovec jsem přepsal do samostatného issue #6 .
