### ISSUE TITLE
Rozměr tisku značek SVG

### ISSUE THREAD

**Issue by raugustyn** [raugustyn/BetaNM#5]
Tomáš: nějak se nám nedaří vytvořit a správně převést ty značky SVG. Posílám jednu testovací značku, kterou jsme vytvořili v programu Inkscape. Je v rozměrech, které odpovídají vyhlášce, ovšem když ji převedeme do QGISu, tak se při tisku nezobrazuje v tom rozměru, v jakém by měla a nemůžeme přijít na to, kde je problém. Jestli přímo v tom editoru a nějakém špatném nastavení podkladu, nebo je někde chyba při importu do QGISu…tohle by bylo potřeba urychleně vyřešit, aby se mohl zbytek značek dokreslit a vizualizovat. Bylo by fajn, kdyby se Vám třeba podařilo vytvořit alespoň jednu značku, tak jak by měla být, abychom se od toho mohli odrazit a dodělat ten zbytek.

 Jinak značka, kterou posílám, je značka pro ovocný sad, kde by měl být při tisku průměr toho kroužku 1,5 mm a svislá čára 0,5 mm. Do těchto rozměrů se nám to v QGISu nepodařilo dát a nevíme proč.

https://github.com/raugustyn/BetaNM/blob/master/Heap/ovocny_sad_pok.svg

**Comment by raugustyn** [comment]
Ta značka vypadá na první pohled špatně. Jak jsem říkal, plátno si musíte navrhnout veliké tak, aby značka byla od okraje k okraji. Vy tam máte přesah. Taky jste si tam dali do SVG značky rastrový obrázek, což asi pro nultou fázi lze, ale potom to bude nutný překreslit, aby byly při tisku hrany čistý.

**Comment by raugustyn** [comment]
Namaluju Vám tuhle jednu značku jako vzor a připojím do QGIS-u, potřebuju však vědět:
- výška značky je 2mm mezi okraji kresby?
- šířka značky je 1.5mm mezi okraji kresby?
- tloušťka čáry podle obrázku?
- jaký teda máte tiskový měřítko toho Tymákova?

Oky?

**Comment by raugustyn** [comment]
Co takhle? [Značka stromu](https://github.com/raugustyn/BetaNM/wiki/Tvorba-SVG-zna%C4%8Dky-stromu)

**Comment by rmakovec** [comment]
v tom odkazu nic nevidím
je to definované v příloze 10 vyhlášky 357/2013 Sb.
pošlu vám mailem co mám par co jsem vytvořil, ty základní, které mám problém zobrazit ve správné rozměru na dvou různých linií, na kterých ale mají vypadat stejně.

**Comment by raugustyn** [comment]
Upravil jsem odkaz [Značka stromu](https://github.com/raugustyn/BetaNM/wiki/Tvorba-SVG-zna%C4%8Dky-stromu)

**Comment by raugustyn** [comment]
Jestliže Tomáš píše, že ta značka má mít kolečko veliké 1.5 mm, což je tedy šířka značky, postačí nastavit rozměr  2m pro měřítko 1:1 000. Samozřejmě značka musí být [tahle](https://raw.githubusercontent.com/raugustyn/BetaNM/master/Heap/ovocny_sad_03.svg). Potom to sedne.

**Comment by raugustyn** [comment]
To @rmakovec: Přílohu mailu jsem vám nahrnul do adresáře MakBodoveZnacky. projdete fakt nejdřív ten příklad [bodový značky](https://github.com/raugustyn/BetaNM/wiki/Tvorba-SVG-zna%C4%8Dky-stromu), teprve potom přejděte na body na liniích. hodnota size je vždy šířka.

Jinak ty značky co jste nakreslil mají všechny nějakou drobnou vadu, to nikdy nemůže sednout! Když vyberete celou kresbu, musí začínat na 0,0 a 'File | Document Properties | Size' musí být přesně stejná jako 'size' tý vybraný kresby.

**Comment by rmakovec** [comment]
můžete se na ty vady SVG značek podívat s Tomášem, já mám ještě co dělat na kreslení vzorových dat
jinak rozměry mám snad OK, měřítko je 1:500
