### ISSUE TITLE
Značky se nenačtou při znovuotevření QGIS

### ISSUE THREAD

**Issue by raugustyn** [raugustyn/BetaNM#6]
@rmakovec napsal: Navíc aktuální případ, že po znovu otevření projektu QGISu se SVG značky nenačtou a je to ztracené. Musím to dělat znovu. Asi to udělám znovu v QGIS 2.4. protože ta 2.8 co je v testování je chybová. Ale vizualizace se tam dělá lépe. Už mi se mi to v tom QGISu ztratilo vícekrát.

**Comment by raugustyn** [comment]
QGIS uchovává podobně jako ArcGIS relativní cesty. Zkuste si stáhnout [repositář](https://github.com/raugustyn/BetaNM/archive/master.zip) a otevřít projekt TestProject03.qgs v adresáři Heap. Mělo by to suše otevřít projekt, data i symboly SVG jak na centroidech tak na obvodu budov.

Je to tak oky?

Jestli jo, tak můžeme hledat dál.

**Comment by rmakovec** [comment]
je to tak

**Comment by rmakovec** [comment]
tak se to zatím načítá
