### ISSUE TITLE
Estetické dotvoření značek

### ISSUE THREAD

**Issue by raugustyn** [raugustyn/BetaNM#8]
Některé značky nejsou úplně vymazlený: slučka, vinice, 3_08_les,  vodní dílo, koryto vodního toku a 2_16_zeď

slučka asi bude vypadat natočená, je potřeba celou překreslit
vinice nemá pěkně napojené čáry nahoře a dole a bude tam zub
atd

**Comment by rmakovec** [comment]
tak ano slučka vypadá trochu natočeně, Vinice je ok, to se v tisku nevidí. Ostatní nevím.

**Comment by rmakovec** [comment]
prosím koukněte se na to s Tomášem, děkuji

**Comment by raugustyn** [comment]
Tak mám pocit že to Mák už dodělal včetně té slučky.
