### ISSUE TITLE
Kontrola tloušťky čáry ve značkách

### ISSUE THREAD

**Issue by raugustyn** [raugustyn/BetaNM#9]
Značky asi mají mít stejnou tloušťku čáry, je to potřeba překontrolovat.

**Comment by rmakovec** [comment]
snad by měli mít všechny tloušťku 0,13, které ne? maximálně jen drobný rozdíl, který se v tisku nepozná

**Comment by raugustyn** [comment]
oky, ten kdo bude mít chvíli může zkontrolovat jestli jsou všechny těch 0.13mm. když budou dvě vedle sebe  tak by to bylo vidět.

**Comment by vacektom** [comment]
zkontrolovány tloušťky čar u všech značek. U těch, kde to nesedělo, jsem je opravil a jsou aktuální tady na Gitu.

**Comment by raugustyn** [comment]
Super, díky. Jenom nezapomínat odlepit nálepku "Otestovat".
